#ifndef CONFIG_H
#define CONFIG_H

// GUI
#define BOARD_EDGE_LEN 50
#define BOARD_HEIGHT 12
#define BOARD_WIDTH 12

// COLOR
// format ABGR
#define GREEN 0xFF73D900
#define BLUE 0xFFFF750D
#define LIGHT_BLUE 0xFFE6FFBF

// GAMEPLAY
#define WATER_SPAWN_RATE 0.15
#define GRASS_SPAWN_RATE 0.5
#define AMANT_SPAWN_RATE 0.1

#endif
