#ifndef CONFIG_H
#define CONFIG_H

// GUI
#define WIDTH 1080
#define HEIGHT 720

#define BOARD_EDGE_LEN 30
#define BOARD_HEIGHT 24
#define BOARD_WIDTH 24

#define TITLE_HEIGHT 120
#define TITLE_WIDTH 360
#define TITLE_WIDTH_SHIFT (BOARD_WIDTH * BOARD_EDGE_LEN)
#define TITLE_HEIGHT_SHIFT 0

#define TITLE_TEXT_WIDTH_SHIFT (TITLE_WIDTH_SHIFT + 20)
#define TITLE_TEXT_HEIGHT_SHIFT (TITLE_HEIGHT_SHIFT + 15)

#define TITLE_CHARACTERS_BY_LINE 18
#define TITLE_CHARACTERS_MAX_LINE_COUNT 4

#define GOD_INTERVENTION_WIDTH TITLE_WIDTH
#define GOD_INTERVENTION_HEIGHT (HEIGHT - TITLE_HEIGHT)
#define GOD_INTERVENTION_WIDTH_SHIFT TITLE_WIDTH_SHIFT
#define GOD_INTERVENTION_HEIGHT_SHIFT (TITLE_HEIGHT_SHIFT + TITLE_HEIGHT)

// COLOR
// format ABGR
#define BACKGROUND_COLOR 0xFF181818
#define GREEN 0xFF73D900
#define BLUE 0xFFFF750D
#define LIGHT_BLUE 0xFFE6FFBF
#define WHITE 0xFFFFFFFF

// GAMEPLAY
#define WATER_SPAWN_RATE 0.15
#define GRASS_SPAWN_RATE 0.5
#define AMANT_SPAWN_RATE 0.1

#endif
