#ifndef CONFIG_H
#define CONFIG_H

// GUI
#define WIDTH 1080
#define HEIGHT 720

#define BOARD_EDGE_LEN 30
#define BOARD_HEIGHT 24
#define BOARD_WIDTH 24

#define TITLE_HEIGHT 120
#define TITLE_WIDTH 360
#define TITLE_WIDTH_SHIFT (BOARD_WIDTH * BOARD_EDGE_LEN)
#define TITLE_HEIGHT_SHIFT 0

#define TITLE_TEXT_WIDTH_SHIFT (TITLE_WIDTH_SHIFT + 20)
#define TITLE_TEXT_HEIGHT_SHIFT (TITLE_HEIGHT_SHIFT + 15)

#define TITLE_CHARACTERS_BY_LINE 18
#define TITLE_CHARACTERS_MAX_LINE_COUNT 4

#define GOD_INTERVENTION_WIDTH TITLE_WIDTH
#define GOD_INTERVENTION_HEIGHT (HEIGHT - TITLE_HEIGHT)
#define GOD_INTERVENTION_WIDTH_SHIFT TITLE_WIDTH_SHIFT
#define GOD_INTERVENTION_HEIGHT_SHIFT (TITLE_HEIGHT_SHIFT + TITLE_HEIGHT)

#define GOD_INTERVENTION_MAX_DISPLAY 6
#define GOD_INTERVENTION_UNITY_HEIGHT (GOD_INTERVENTION_HEIGHT / GOD_INTERVENTION_MAX_DISPLAY)

#define GOD_INTERVENTION_TEXT_WIDTH_SHIFT (GOD_INTERVENTION_WIDTH_SHIFT + 20)
#define GOD_INTERVENTION_TEXT_HEIGHT_SHIFT (GOD_INTERVENTION_HEIGHT_SHIFT + 15)
#define GOD_INTERVENTION_MAX_LINE_CHARACTERS 15

// COLOR
// format ABGR
#define BACKGROUND_COLOR 0xFF181818
#define BLUE 0xFFFF750D
#define CALAMINE_BLUE 0XFFCCFF80
#define GREEN 0xFF73D900
#define PALE_LEMON_YELLOW 0xFF9EF5FF
#define POMEGRANATE_PURPLE 0xFF7800B9
#define WHITE 0xFFFFFFFF
#define YELLOW_GREEN 0xFF47FFA6
#define AMANT_COLOR 0x7F26FFF2

// GAMEPLAY
#define WATERPOOL_INIT_COUNT 5
#define WATERPOOL_MIN_RADIUS 1
#define WATERPOOL_MAX_RADIUS 5

#define WATER_SPAWN_RATE 0.05
#define GRASS_SPAWN_RATE1 0.01 // from EMPTY
#define GRASS_SPAWN_RATE2 0.1  // close to WATER
#define AMANT_SPAWN_RATE 0.01
#define GRASS_IGNITE_RATE 0.01
#define FIRE_EXTINGUISHMENT_RATE 0.99
#define FIRE_TRANSMISSION_RATE 0.99

#define BOARD_MAX_SEARCHING_DEPTH 3
#define AMANT_LIST_SIZE 32
#define AMANT_MAX_MISSION_COUNT 30

#endif
